# i3lock palette

inside_color=F2EDE3DD
ring_color=4A6280FF
line_color=00000000
separator_color=00000000

insidever_color=E5DED3DD
insidewrong_color=E5DED3DD

ringver_color=4F6B4AFF
ringwrong_color=A33A3AFF

keyhl_color=9A761FFF
bshl_color=B8B1A6FF

time_color=292724FF
date_color=5C5954FF
layout_color=4F7474FF

verif_color=4A6280FF
wrong_color=A33A3AFF
