# Backend
backend = "glx";
vsync = true;

# Sombras
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.4;
shadow-offset-x = -12;
shadow-offset-y = -8;
shadow-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Dunst'",
    "name = 'Notification'",
    "fullscreen"
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 7;

# Transparência
# Opacidade inativa geral (deixe 1.0 para performance ou algo como 0.95)
inactive-opacity = 1.0;
# Opacidade específica por aplicativo
opacity-rule = [
    "90:class_g = 'kitty'",
    "90:class_g = 'Thunar'",
    "95:class_g = 'firefox'"
];

# Otimizações
glx-copy-from-front = false;
unredir-if-possible = true; # Melhora performance em fullscreen

# Blur (se seu hardware aguentar)
# blur-method = "dual_kawase";
# blur-strength = 8;
# blur-background = true;
