Net/ThemeName "catppuccin-mocha-blue-standard+default"
Net/IconThemeName "Papirus-Dark"
Gdk/CursorThemeName "Bibata-Modern-Classic"
Gdk/WindowScalingFactor 1
Gtk/FontName "JetBrainsMono Nerd Font 10"
Gtk/ColorScheme "prefer-dark"
Gtk/CursorThemeSize 24
Gtk/EnableAnimations 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"