# Borders
default_border pixel 0
default_floating_border pixel 0

# Gaps
gaps inner 4
gaps outer 1
smart_gaps off

# Theme Colors
client.focused          #4A6280 #F2EDE3 #292724 #4A6280 #4A6280
client.unfocused        #B8B1A6 #E5DED3 #5C5954 #E5DED3 #B8B1A6
client.focused_inactive #9A761F #F2EDE3 #292724 #F2EDE3 #9A761F
client.urgent           #A33A3A #F2EDE3 #292724 #A33A3A #A33A3A

# PaperColor Colors
set $bg         #F2EDE3
set $bg-alt     #E5DED3

set $accent     #4A6280
set $accent2    #9A761F

set $ink        #292724
set $gray       #5C5954
set $gray-light #B8B1A6
set $red        #A33A3A
